config/routes.rb
FuseMe::Application.routes.draw do

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  resources :tasks, :only => [:show, :destroy, :create, :update, :new, :edit]
  match '/sync_facebook' => 'integrations#sync_facebook', :as => 'sync_facebook'
  
  resources :profiles, :only => [:update, :edit]
  match '/me' => 'profiles#me', :as => 'me'

  resources :connections, :only => [:destroy, :create]
  match '/contacts' => 'connections#index', :as => 'contacts'
  
  devise_for :users
  match '/settings' => 'users#settings', :as => 'settings'

  resources :integrations, :only => [:new,:destroy,:create, :index]
  match 'auth/:provider/callback' => 'integrations#create'
  match '/dashboard' => 'tasks#dashboard', :as => 'dashboard'
  match '/sync_all' => 'integrations#sync_all', :as => 'sync_all'
  
  
  root :to => "tasks#dashboard"

  match '/profiles/:id' => 'profiles#full_contact_profile', :as => 'full_contact_profile'

end

app/models/profile.rb
class Profile < ActiveRecord::Base
  #Associations
  	belongs_to :user, :inverse_of => :profile

  #Attributes
  	attr_accessible :first_name, :image, :last_name, :user_id, :user_name, :remote_image_url

  #Callbacks
    before_save { |profile| profile.user_name = profile.user_name.downcase }

  #Scopes
    scope :default_profile_order, order(:first_name).order(:last_name)

  #Other
	mount_uploader :image, ImageUploader

  #Validation
  validates :user_name, :presence => true
  validates :user_name, :format => { :with => /^\w+$/i,
    :message => "only letters and numbers allowed" }
  validates :user_name, :exclusion => {:in => %w(contact dashboard profile profiles ass dick cunt prick shit fuck connection contacts connections home), :message => "Please choose a different user name"} 
  validates :user_name, :length => {:maximum => 50, :too_long => "%{count} characters is the maximum allowed"}
  validates :user_name, :length => {:minimum => 4, :too_short => "%{count} characters is the manimum allowed"}
  validates :user_name, :uniqueness => { :case_sensitive => false }

	def full_name
      "#{self.first_name} #{self.last_name}"
  end

  def full_name=(fullname)
      first,last = fullname.split(' ')  # or some smarter way to split
      self.first_name = first
      self.surname = last
  end

  #When adding a new contact and you have contacts already
  def self.list_profiles_to_add(user_id)
    user = User.find(user_id)
    where(user_id: User.select("id")).where("profiles.user_id not in (?)",user.contacts.select("contact_id").map(&:contact_id)).where("profiles.user_id !=?",user.id)
  end
  #When adding a new contact and you have no contacts
  def self.list_profiles_to_add_when_no_others(user_id)
    user = User.find(user_id)
    where(user_id: User.select("id")).where("profiles.user_id !=?",user.id)
  end

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
#Rails.logger.info("PARAMS: #{params.inspect}")   
  
  before_filter :require_login

  def require_login
    unless user_signed_in?
      redirect_to new_user_session_path, flash: {:error => "You must be logged in to continue to access this section"}
    end
  end

   def me
    @profile = Profile.find_by_user_id(current_user.id)

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @profile }
    end
  end
  
  def full_contact_profile  #Will render the view that a user sees when they view a contact

    #Get the appropriate profile based on the user_name passed
    #@profile = Profile.find_by_user_name(params[:user_name].downcase)
    @profile = Profile.find_by_id(params[:id])

    #Prepare the list of tasks shared between current_user and this profile
    user_id = current_user.id
    sender_id = @profile.user_id
    @tasks = Task.dialog(user_id, sender_id).default_task_order

    if @profile.nil? or Connection.find_by_user_id_and_contact_id(current_user.id, @profile.user_id).nil?
      then
        respond_to do |format|
          format.html { redirect_to '/dashboard', notice: 'You cannot view that page' }
         
        end
    else
        respond_to do |format|
          format.html # show.html.erb
          format.json { render json: @profile }
       end     
    end
 
  end
 
  # GET /profiles/new
  # GET /profiles/new.json
  def new
    @profile = Profile.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @profile }
    end
  end

  # GET /profiles/1/edit
  def edit  
    @profile = Profile.find(params[:id])
  end

  # POST /profiles
  # POST /profiles.json
  def create
    @profile = Profile.new(params[:profile])

    respond_to do |format|
      if @profile.valid? and @profile.save
        format.html { redirect_to '/me', notice: 'Profile was successfully created.' }
        format.json { render json: @profile, status: :created, location: @profile }
      else
        format.html { render action: "new" }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /profiles/1
  # PUT /profiles/1.json
  def update
    @profile = Profile.find(params[:id])

    respond_to do |format|
      if @profile.update_attributes(params[:profile])
        format.html { redirect_to '/me', notice: 'Profile was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

end

app/helpers/profiles_helper.rb
module ProfilesHelper

end

app/views/profiles/_form.html.erb
<%= form_for @profile, :html => {:multipart => true} do |f| %>
  <% if @profile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@profile.errors.count, "error") %> prohibited this profile from being saved:</h2>

      <ul>
      <% @profile.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br />
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br />
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :user_name %><br />
    <%= f.text_field :user_name %>
  </div>
  <div class="field">
    <%= f.label :image %><br />
    <%= f.file_field :image %>
    <%= image_tag @profile.image_url(:thumb).to_s if @profile.image? %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/profiles/_profile.html.erb
<p>
  <b>First name:</b>
  <%= @profile.first_name %>
</p>

<p>
  <b>Last name:</b>
  <%= @profile.last_name %>
</p>

<% if User.find_by_id(@profile.user_id).stub == false %>
	<p>
	  <b>User name:</b>
	  <%= @profile.user_name %>
	</p>
<% end %>

<p>
  <b>Headshot:</b>
  <%= image_tag @profile.image_url(:thumb).to_s if @profile.image? %>
</p>

app/views/profiles/_small_profile.html.erb
<div name ="small_profile">
	<div name = "sp_photo"> 			
		<%=image_tag profile.image_url(:thumb).to_s if profile.image? %> 
	  	<div name ="sp_name"> 
	  		<%=link_to profile.full_name, full_contact_profile_path(profile.user_name) %> 
	  	</div>
	</div>
</div>

app/views/profiles/edit.html.erb
<h1>Editing profile</h1>

<%= render 'form' %>

app/views/profiles/full_contact_profile.html.erb
<%= render "profile" %>

<%= render "/tasks/dialog" %>

<%= link_to 'New Message', new_task_path(:user_id => @profile.user_id) %>

app/views/profiles/index.html.erb
<h1>Listing profiles</h1>

<table>
  <tr>
    <th>First name</th>
    <th>Last name</th>
    <th>Image</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @profiles.each do |profile| %>
  <tr>
    <td><%= profile.first_name %></td>
    <td><%= profile.last_name %></td>
    <td><%= profile.image %></td>
    <td><%= link_to 'Show', profile %></td>
    <td><%= link_to 'Edit', edit_profile_path(profile) %></td>
    <td><%= link_to 'Destroy', profile, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Profile', new_profile_path %>

app/views/profiles/me.html.erb
<p id="notice"><%= notice %></p>
<h1>Your Profile</h1>
<br />
<br />
<%= render "profile" %>

<%= link_to 'Edit', edit_profile_path(@profile) %>

app/views/profiles/new.html.erb
<h1>New profile</h1>

<%= render 'form' %>

app/views/profiles/show.html.erb
<%= render "profile" %>