config/routes.rb
FuseMe::Application.routes.draw do

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  resources :tasks, :only => [:show, :destroy, :create, :update, :new, :edit]
  match '/sync_facebook' => 'integrations#sync_facebook', :as => 'sync_facebook'
  
  resources :profiles, :only => [:update, :edit]
  match '/me' => 'profiles#me', :as => 'me'

  resources :connections, :only => [:destroy, :create]
  match '/contacts' => 'connections#index', :as => 'contacts'
  
  devise_for :users
  match '/settings' => 'users#settings', :as => 'settings'

  resources :integrations, :only => [:new,:destroy,:create, :index]
  match 'auth/:provider/callback' => 'integrations#create'
  match '/dashboard' => 'tasks#dashboard', :as => 'dashboard'
  match '/sync_all' => 'integrations#sync_all', :as => 'sync_all'
  
  
  root :to => "tasks#dashboard"

  match '/profiles/:id' => 'profiles#full_contact_profile', :as => 'full_contact_profile'

end

app/models/task.rb
class Task < ActiveRecord::Base
	attr_accessible :title, :body, :location, :start_time, :end_time,
		:task_type, :system, 
		:user_id, :sent, :read, :read_time, :sent_time, :status,
		:status_time, :task_group_id, :sender_id, :previous_system_id, :transmitted_at
	
	#Associations
	belongs_to :receiver, :class_name => 'User', :foreign_key => 'user_id', :inverse_of => :received_tasks
	belongs_to :sender, :class_name => 'User', :foreign_key => 'sender_id', :inverse_of => :sent_tasks
	belongs_to :task_group, :inverse_of => :tasks

	#Callbacks
	after_save { |task| task.transmitted_at = Time.now.to_i }

 	#Validations
	validates :user_id, :presence => true
	validates :sender_id, :presence => true
	validates :title, :presence => true

	#Scopes
	scope :default_task_order, :order => ("tasks.transmitted_at desc" )

	#Get the dialog between the sender and receiver
	def self.dialog(user_id, sender_id)
		where("(user_id = ? and sender_id = ?) or (user_id = ? and sender_id = ?)" , user_id, sender_id, sender_id, user_id)
	end

	def read!
		self.read = true
		self.read_time = Time.now
		self.save
	end

end

app/controllers/tasks_controller.rb
#Rails.logger.info("PARAMS: #{params.inspect}")   
class TasksController < ApplicationController
  include ApplicationHelper

  before_filter :require_login


  def require_login
    unless user_signed_in?
      redirect_to new_user_session_path, flash: {:error => "You must be logged in to continue to access this section"}
    end
  end

  def dashboard    
    @tasks = current_user.received_tasks.default_task_order
    
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tasks }
    end
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
    @show_task = Task.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @task }
    end
  end

  # GET /tasks/new
  # GET /tasks/new.json
  def new
    @task = Task.new

    #Grab params
    @task.user_id = params[:user_id] if not params[:user_id].nil? and current_user.contacts.exists?(params[:user_id])
    task_id = params[:task]    

    #Make sure the task specified to reply to is for one I've sent or receieved
    if task_id != nil then
      if current_user.sent_tasks.exists?(task_id) or current_user.received_tasks.exists?(task_id)
        @old_task = Task.find(task_id)
        @task.user_id = @old_task.sender_id
        @task.task_group_id = @old_task.task_group_id
        @task.title = @old_task.title
      end
    end

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @task }
    end
  end

  # GET /tasks/1/edit
  def edit
    @task = Task.find(params[:id])
  end

  # POST /tasks
  # POST /tasks.json
  def create
    #Rails.logger.info("PARAMS: #{params.inspect}")
    @task = Task.new(params[:task])
    @task.sent_time = Time.now
    @task.read = false
    @task.sender_id = current_user.id
    if @task.task_group_id.nil?
      then
        task_group = TaskGroup.new()
        task_group.save
        @task.task_group_id = task_group.id
    end

    respond_to do |format|
      if @task.save #Save the sending Task
          format.html { redirect_to @task, notice: 'Task was successfully created.' }
          format.json { render json: @task, status: :created, location: @task }
        else
          @task.destroy
          format.html { render action: "new" }
          format.json { render json: @task.errors, status: :unprocessable_entity }
        end
      end
  end

  # PUT /tasks/1
  # PUT /tasks/1.json
  def update
    @task = Task.find(params[:id])

    respond_to do |format|
      if @task.update_attributes(params[:task])
        format.html { redirect_to @task, notice: 'Task was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task = Task.find(params[:id])
    @task.destroy

    respond_to do |format|
      format.html { redirect_to :back }
      format.json { head :no_content }
    end
  end

end

app/helpers/tasks_helper.rb
module TasksHelper

end

app/views/tasks/_dialog.html.erb
<h1>Communication Dialog</h1>
<table>
  <tr>
    <th>To</th>
    <th>From</th>

    <th>Title</th>
    <th>Body</th>
    <th>System</th>
    <th>Task Type</th>
    <th>Sent</th>

    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @tasks.each do |task| %>
  <tr>
    <td><%= display_name(task.user_id) %></td>
    <td><%= display_name(task.sender_id) %></td>
    <td><%= task.title %></td>
    <td><%= task.body %></td>
    <td><%= task.system %></td>
    <td><%= task.task_type %></td>
    <td><%= display_stepped_datetime(task.transmitted_at) %></td>
    <td><%= link_to 'Show', task, query: "fo" %></td>
    <td><%= link_to 'Destroy', task, data: {confirm: 'Are you sure?'}, method: :delete %></td>
    <td><% if current_user.id == task.user_id then%> 
          <%= link_to 'Reply', new_task_path(:task => task) %> 
        <% end %></td>
  </tr>
<% end %>

</table>

app/views/tasks/_form.html.erb
<%= form_for(@task) do |f| %>
  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% @task.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

 <div class="field">
    <%= label :user_id, "To" %><br />
    <%= f.collection_select :user_id, Profile.where(user_id: current_user.contacts.select("connections.contact_id")).default_profile_order, :user_id, :full_name, {}, {multiple: false, :include_blank => false} %> 
  </div>
 
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title, :value => if params[:action] == "reply" then  @show_task.title else @task.title end  %>
  </div>
  <div class="field">
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </div>
  <div class="field">
    <%= f.text_field :task_type, :value =>"EMail" %>
  </div>
  <div class="field">
    <%= f.text_field :system, :value =>"Fuse" %>
  </div>

  <div class="actions">
    <%= f.submit "Send Message" %>
  </div>
<% end %>

app/views/tasks/_show_task.html.erb
<p>
  <b>To:</b>
 	<%= display_name(@show_task.user_id) %>
</p>
<p>
  <b>From:</b>
   	<%= display_name(@show_task.sender_id) %>
</p>

<p>
  <b>Title:</b>
  <%= @show_task.title %>
</p>
<p>
  <b>Body:</b>
  <%= @show_task.body %>
</p>

<% if @show_task.sent then %>
<p>
  <b>Date Sent:</b>
  <%= @show_task.sent_time %>
</p>
<% else %>
 <p>
  <b>Date Received:</b>
  <%= @show_task.sent_time %>
</p>
<% end %>

app/views/tasks/dashboard.html.erb
<h1>Your Dashboard</h1>
<br/>
<%= link_to 'Sync All Messages', sync_all_path() %>
<br/>
<%= link_to 'New Message', new_task_path() %>
<br/>
<table>
  <tr>
    <th>From</th>
    <th>Title</th>
    <th>Body</th>
    <th>System</th>
    <th>Task Type</th>
    <th>Sent</th>

    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @tasks.each do |task| %>
  <tr>
    <td><%= link_to task.sender.profile.full_name, full_contact_profile_path(task.sender.profile.id) %></td>
    <td><%= task.title %></td>
    <td><%= task.body %></td>
    <td><%= task.system %></td>
    <td><%= task.task_type %></td>
    <td><%= display_stepped_datetime(task.transmitted_at)%></td>

    <td><%= link_to 'Show', task, query: "fo" %></td>
    <td><%= link_to 'Destroy', task, :data => {:confirm => 'Are you sure?'}, method: :delete %></td>
    <td><% if current_user.id == task.user_id then%> 
          <%= link_to 'Reply', new_task_path(:task => task) %> 
        <% end %>
    </td>
  </tr>
<% end %>
</table>
<br />

app/views/tasks/edit.html.erb
<h1>Editing task</h1>

<%= render 'form' %>

<%= link_to 'Show', @task %> |
<%= link_to 'Back', tasks_path %>

app/views/tasks/index.html.erb
<h1>Listing tasks</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @tasks.each do |task| %>
  <tr>
    <td><%= link_to 'Show', task %></td>
    <td><%= link_to 'Edit', edit_task_path(task) %></td>
    <td><%= link_to 'Destroy', task, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Task', new_task_path %>

app/views/tasks/new.html.erb
<h1>New task</h1>

<%= render 'form' %>

app/views/tasks/reply.html.erb
<p id="notice"><%= notice %></p>

<%= render "show_task" %>

<br />
<br />


<%= form_for(@task) do |f| %>
  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% @task.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<%= render "form" %>

<% end %>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<%= render "show_task" %>

<% if current_user.id == @show_task.user_id %>
	<%= link_to 'Reply', new_task_path(:task => @show_task) %>
<% end %>