config/routes.rb
FuseMe::Application.routes.draw do

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  resources :tasks, :only => [:show, :destroy, :create, :update, :new, :edit]
  match '/sync_facebook' => 'integrations#sync_facebook', :as => 'sync_facebook'
  
  resources :profiles, :only => [:update, :edit]
  match '/me' => 'profiles#me', :as => 'me'

  resources :connections, :only => [:destroy, :create]
  match '/contacts' => 'connections#index', :as => 'contacts'
  
  devise_for :users
  match '/settings' => 'users#settings', :as => 'settings'

  resources :integrations, :only => [:new,:destroy,:create, :index]
  match 'auth/:provider/callback' => 'integrations#create'
  match '/dashboard' => 'tasks#dashboard', :as => 'dashboard'
  match '/sync_all' => 'integrations#sync_all', :as => 'sync_all'
  
  
  root :to => "tasks#dashboard"

  match '/profiles/:id' => 'profiles#full_contact_profile', :as => 'full_contact_profile'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FuseMe</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
       <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>
</br>
<ul class="hmenu">
  <li> <%= link_to 'Dashboard', '/dashboard#index' %></li> 
  <li> <%= link_to 'Profile', me_path() %></li> 
  <li> <%= link_to 'Contacts', '/contacts' %></li> 
  <li> <%= link_to 'Integrations', '/integrations' %></li> 
  <%= render 'devise/menu/registration_items' %>
  <%= render 'devise/menu/login_items' %>
</ul>
<%= yield %>
<br />
<br />

</body>
</html>